# Generated by Django 5.0 on 2023-12-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('symptoms_image', models.ImageField(blank=True, null=True, upload_to='mhlblogs/mental_health_images/')),
                ('symptoms1_title', models.TextField(blank=True)),
                ('symptoms1_description', models.TextField(blank=True)),
                ('symptoms2_title', models.TextField(blank=True)),
                ('symptoms2_description', models.TextField(blank=True)),
                ('symptoms3_title', models.TextField(blank=True)),
                ('symptoms3_description', models.TextField(blank=True)),
                ('treatments_image', models.ImageField(blank=True, null=True, upload_to='mhlblogs/mental_health_images/')),
                ('treatment1_title', models.TextField(blank=True)),
                ('treatment1_description', models.TextField(blank=True)),
                ('treatment2_title', models.TextField(blank=True)),
                ('treatment2_description', models.TextField(blank=True)),
                ('treatment3_title', models.TextField(blank=True)),
                ('treatment3_description', models.TextField(blank=True)),
            ],
        ),
    ]
