# Generated by Django 5.0 on 2023-12-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhlblogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthillness',
            name='author',
            field=models.ImageField(blank=True, null=True, upload_to='mhlblogs/mental_health_images/'),
        ),
        migrations.AddField(
            model_name='mentalhealthillness',
            name='date_created',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentalhealthillness',
            name='main_bg',
            field=models.ImageField(blank=True, null=True, upload_to='mhlblogs/mental_health_images/'),
        ),
    ]
