# Generated by Django 5.0 on 2023-12-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhlblogs', '0003_mentalhealthillness_author_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalhealthillness',
            name='slogan',
            field=models.TextField(blank=True),
        ),
    ]
